Repository Team-ThreeGo/Algo-Data, pull requests merged in 2025-09, with the labels that each got.

#16 [Feat] #13 - 스터디모집 관련 기능 조회 쿼리 작성
  queries/08_studyrecruit_queries.sql
Labels: 스터디

#27 [Fix] #26 - 신고 및 코딩 풀이 DDL 수정
  ddl/ddl_script.sql
  ddl/modules/03_coding_tables.sql
  ddl/modules/06_study_tables.sql
  ddl/modules/07_report_tables.sql
  samples/03_coding_samples.sql
  samples/07_report_samples.sql
Labels: Hotfix, 코딩 풀이, 신고

#21 [Feat] #18 - 회원 관련 조회 쿼리 작성
  queries/01_member_queries.sql
  queries/07_report_queries.sql
Labels: 회원

#30 [Feat] #29 - 스터디 게시물,댓글 조회 기능(관리자)
  queries/06_study_queries.sql
Labels: 스터디

#28 [Fix] #13 - 스터디모집 관련 기능 조회쿼리 관리자 추가(게시물조회,상세조회,댓글조회)
  queries/08_studyrecruit_queries.sql
Labels: Hotfix, 스터디
